name: Smite
version: ${project.version}
main: com.bghddevelopment.smite.Smite
authors: [BGHDDevelopment]
website: https://bghddevelopment.com/
commands:
  smite:
    description: Smite Player
    usage: /<command> <player>